// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchAnyBreed() {
  return window['go']['main']['App']['FetchAnyBreed']();
}

export function FetchByBreed(arg1) {
  return window['go']['main']['App']['FetchByBreed'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SelectBreed() {
  return window['go']['main']['App']['SelectBreed']();
}
