// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchAnyBreed():Promise<{[key: string]: string}>;

export function FetchByBreed(arg1:string):Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function SelectBreed():Promise<Array<string>>;
